### ISSUE TITLE
Remove node-todo example

### ISSUE THREAD

**Issue by chipotle** [rethinkdb/docs#1050]
This is going to require three steps:

- [x] edit `examples.md` to link to the Github repository w/proper description
- [x] remove the actual node-todo files
- [x] change any links to `/docs/examples/node-todo` through the rest of the docs site
